#!/usr/bin/env python3
import os
import sys

import click

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from base import search  # noqa: E402


@click.command()
@click.option("--verbose", is_flag=True, default=False)
def main(*, verbose):
    updated, total = search.update_index(verbose=verbose)
    print(f"Updated {updated} document(s) out of {total}.")


if __name__ == "__main__":
    main()
